---
kind: pipeline
type: docker
name: default

trigger:
  event:
    exclude:
      - pull_request

steps:

###
### Mirror the current repository state to Github
###

- name: github-mirror
  image: alpine
  environment:
    SSH_PUBKEY:
      from_secret: ssh_pubkey
    SSH_PRIVKEY:
      from_secret: ssh_privkey

  when:
    branch:
      - main
    event:
      - push

  commands:
    - . .drone/github-mirror.sh

###
### Lint
###

- name: backend-lint
  image: python:3.12
  commands:
    - pip install flake8 black isort mypy
    - python -m flake8 songhive tests
    - python -m black --check .
    - python -m isort songhive tests
    - python -m mypy songhive

  when:
    event:
      - push
    paths:
      include:
        - songhive/**

###
### Run tests
###

- name: backend-tests
  image: python:3.14
  commands:
    - apt-get update && apt-get install -y ffmpeg
    - pip install -e . -r requirements-dev.txt
    - python -m pytest --cov=songhive --cov-report=term-missing --cov-report=xml

  when:
    event:
      - push
    paths:
      include:
        - songhive/**

###
### Frontend Lint
###

- name: frontend-lint
  image: node:20
  commands:
    - cd frontend && npm ci && npm run lint
  when:
    event:
      - push
    paths:
      include:
        - frontend/**

###
### Frontend tests
###

- name: frontend-tests
  image: node:20
  commands:
    - cd frontend && npm ci && npm run test
  when:
    event:
      - push
    paths:
      include:
        - frontend/**

###
### Upload test coverage to Codacy
###

- name: codacy-coverage
  image: python:3.12
  depends_on:
    - github-mirror
    - backend-tests
  when:
    branch:
      - main
    event:
      - push
    paths:
      include:
        - songhive/**

  environment:
    CODACY_PROJECT_TOKEN:
      from_secret: codacy_project_token
  commands:
    - curl -fsSL https://coverage.codacy.com/get.sh -o /tmp/codacy-coverage.sh
    - bash /tmp/codacy-coverage.sh report -r coverage.xml --commit-uuid "$DRONE_COMMIT_SHA"
