[project]
name = "songhive"
description = "A federated and self-hosted music sharing service"
dynamic = ["version", "dependencies"]
authors = [
  {name = "Fabio Manganiello", email = "fabio@manganiello.tech"},
]

classifiers=[
    "Topic :: Utilities",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Development Status :: 3 - Alpha",
]

readme = "README.md"
requires-python = '>= 3.10'
keywords = [
  "music",
  "activitypub",
  "fediverse",
  "indieweb",
  "streaming",
]

[tool.setuptools.dynamic]
version = {attr = "songhive.__version__"}
dependencies = {file = "requirements.txt"}

[project.urls]
homepage = "https://git.platypush.tech/blacklight/songhive"
repository = "https://git.platypush.tech/blacklight/songhive"

[project.scripts]
songhive = 'songhive:main'

[tool.setuptools.packages.find]
include = ["songhive*"]

[tool.setuptools.package-data]
"songhive" = ["static/**/*"]
"songhive.migrations" = ["*.mako", "versions/*.py"]

[tool.black]
line-length = 120
target-version = ['py310']

[tool.bumpversion]
current_version = "0.0.12"
commit = true
tag = true

[[tool.bumpversion.files]]
filename = "CHANGELOG.md"
search = "Unreleased"

[[tool.bumpversion.files]]
filename = "songhive/version.py"

[tool.mypy]
python_version = "3.10"
warn_return_any = false
warn_unused_configs = true
disallow_untyped_defs = false
check_untyped_defs = true
ignore_missing_imports = true

[tool.isort]
profile = "black"
line_length = 120
